'use strict';
/*ESTE ARCHVIO CONTIENE EL CONTADOR DE LOS USUARIOS QUE SE REGISTRAN EN GENERAL. 
DUEÑOS DE PARQUEO, EMPRESAS Y CLIENTES NORMALES. 
ESTE ARCHVIO DEBE ESTAR EN TODOS LOS ARCHVIOS DE REGISTRO.*/
let contador_usuario_registrado_general = 0;
export { contador_usuario_registrado_general };